const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desk', {
  getState: function () { return ipcRenderer.invoke('state:get'); },
  onState: function (fn) { ipcRenderer.on('state', function (e, s) { fn(s); }); },
  setInteractive: function (on) { ipcRenderer.send('overlay:interactive', !!on); },
  moveBowl: function (pos) { ipcRenderer.send('bowl:move', pos); },
  feed: function (mode) { ipcRenderer.send('bowl:feed', mode); },
  undoFeed: function () { ipcRenderer.send('bowl:undoFeed'); },
  onUndoFeed: function (fn) { ipcRenderer.on('undoFeed', function () { fn(); }); },
  eatOne: function () { ipcRenderer.send('food:eat'); },
  openMemo: function () { ipcRenderer.send('memo:open'); },
  pushState: function (s) { ipcRenderer.send('state:push', s); },
  onEat: function (fn) { ipcRenderer.on('eat', function () { fn(); }); },
  onFeed: function (fn) { ipcRenderer.on('feed', function (e, mode) { fn(mode); }); },
  onMet: function (fn) { ipcRenderer.on('met', function (e, b) { fn(b); }); },
  onFeedSpecial: function (fn) { ipcRenderer.on('feedSpecial', function () { fn(); }); },
  onGift: function (fn) { ipcRenderer.on('gift', function (e, p) { fn(p); }); },
  reportCats: function (list) { ipcRenderer.send('cats:here', list); },
  onGiftDone: function (fn) { ipcRenderer.on('giftDone', function (e, p) { fn(p); }); },
  metCat: function (b) { ipcRenderer.send('cat:met', b); },
  leftCat: function (b) { ipcRenderer.send('cat:left', b); },
  onLeft: function (fn) { ipcRenderer.on('left', function (e, b) { fn(b); }); },
  onShoot: function (fn) { ipcRenderer.on('shoot', function (e, id) { fn(id); }); },
  onSendAway: function (fn) { ipcRenderer.on('sendAway', function (e, id) { fn(id); }); },
  savePhoto: function (p) { ipcRenderer.send('photo:save', p); },
  onPhoto: function (fn) { ipcRenderer.on('photo', function (e, p) { fn(p); }); },
  bowlMenu: function () { ipcRenderer.send('bowl:menu'); },
  catMenu: function (c) { ipcRenderer.send('cat:menu', c); },
  setSound: function (on) { ipcRenderer.send('sound:set', !!on); },
  onSummon: function (fn) { ipcRenderer.on('summon', function () { fn(); }); },
  notice: function (text) { ipcRenderer.send('notice', text); },
  onNotice: function (fn) { ipcRenderer.on('notice', function (e, t) { fn(t); }); },
  onMemoBounds: function (fn) { ipcRenderer.on('memoBounds', function (e, b) { fn(b); }); },
});
